---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
      statuses: read
    steps:
      - name: Check out
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Run Merge Gatekeeper
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
